development:
  bio_domain: narendran.local
  blog:
    domain: narendran.local
    subdomain: blogs
  greenify:
    domain: narendran.local
    subdomain: greenify
production:
  bio_domain: narendran.me
  greenify:
    domain: narendran.me
    subdomain: project-greenify
  blog:
    domain: narendran.me
    subdomain: blogs